### PR TITLE
Library mode

### PR DESCRIPTION
**Pull request by Narek-Pogosian**
VoiceChat component gets built to 2 formats, voice-chat.js and voice-chat.umd.cjs. For now both of them include the streamingMic.js code in the build.

Vite/rollup doesn't allow multiple entrypoints when building to multiple formats so I have added a seperate build for streamingMic which gets built to a umd file.

### CODE REVIEW

**Comment by ripperdoc** [comment]
Good start! So a couple of things that I see at this stage:
1. The repo has no way of testing that the exported bundles behave as we want. At least, it would be good to have an index.html file that uses what's exported in dist to show that it works.
2. While I prefer if StreamingMic is exported separately, it could work without that. However, StreamingMic still needs to be on the global namespace so that any script can call on it from anywere. There is a line I added `globalThis.StreamingMic = StreamingMic;` which might to this but we should test that it works - otherwise there are settings in rollup to tell what to add to globals.
3. There is a rollup config but I am guessing that it's not used? I think you need to add it inside `vite.config.ts` if you want to use it?
4. An alternative to exporting as umd is to export as es, as modern browsers should handle it. But I am not sure how that works with all sub-dependencies - but right now we have no sub-dependencies which might trick us to thinking it works well. So would be good to add some other minor dependency into package.json, if not just for testing.

**Comment by Narek-Pogosian** [comment]
1. Not sure if this is what you mean but the VoiceChat component is imported in App.tsx in src which during development behaves as normal. We can run npm run dev and the index.html in root renders the App component.
2. The streamingMic.ts code is built into its own file in dist, that's what the rollup config is for as it wasn't possible to use multiple entry points in Vite when exporting to multiple formats.

**Comment by ripperdoc** [comment]
> 1. Not sure if this is what you mean but the VoiceChat component is imported in App.tsx in src which during development behaves as normal. We can run npm run dev and the index.html in root renders the App component.

Thats good, but we also need to test that we can import it as a `<script>`, could be a different `html` file for clarity. And in the case of `web-app`, we should still be able to access `StreamingMic` in `DialogueApp` after using this new import instead of the old way it's imported there.

> 2. The streamingMic.ts code is built into its own file in dist, that's what the rollup config is for as it wasn't possible to use multiple entry points in Vite when exporting to multiple formats.

Ok got it, but there was no commad for that in `package.json` or `README` so may need to add some instructions.

**Comment by Narek-Pogosian** [comment]
StreamingMic code is now not bundled in VoiceChat component, will need to be linked to seperately and it will be available in global scope. In web-app we will need a way to add the streamingMic code either link to in the html file or add it in a top level component with addExternalScript like in dialogueApp so that it will be available both for VoiceChat and there.

**Review by ripperdoc — APPROVED** [review]

**Pull request merged**
